/* This file is automatically generated, do not edit manually! */
const headerStr = "Zowe CLI";
const footerStr = "Release: 1.5.x (stable)";
const treeNodes = [
  {
    "id": "zowe.html",
    "text": "zowe",
    "children": [
      {
        "id": "zowe_cics.html",
        "text": "cics",
        "children": [
          {
            "id": "zowe_cics_define.html",
            "text": "define | def",
            "children": [
              {
                "id": "zowe_cics_define_program.html",
                "text": "program | prog"
              },
              {
                "id": "zowe_cics_define_transaction.html",
                "text": "transaction | tran"
              }
            ]
          },
          {
            "id": "zowe_cics_delete.html",
            "text": "delete | del",
            "children": [
              {
                "id": "zowe_cics_delete_program.html",
                "text": "program | prog"
              },
              {
                "id": "zowe_cics_delete_transaction.html",
                "text": "transaction | tran"
              }
            ]
          },
          {
            "id": "zowe_cics_discard.html",
            "text": "discard | dis",
            "children": [
              {
                "id": "zowe_cics_discard_program.html",
                "text": "program | prog"
              },
              {
                "id": "zowe_cics_discard_transaction.html",
                "text": "transaction | tran"
              }
            ]
          },
          {
            "id": "zowe_cics_get.html",
            "text": "get",
            "children": [
              {
                "id": "zowe_cics_get_resource.html",
                "text": "resource | res"
              }
            ]
          },
          {
            "id": "zowe_cics_install.html",
            "text": "install | ins",
            "children": [
              {
                "id": "zowe_cics_install_program.html",
                "text": "program | prog"
              },
              {
                "id": "zowe_cics_install_transaction.html",
                "text": "transaction | tran"
              }
            ]
          },
          {
            "id": "zowe_cics_refresh.html",
            "text": "refresh | ref",
            "children": [
              {
                "id": "zowe_cics_refresh_program.html",
                "text": "program | prog"
              }
            ]
          }
        ]
      },
      {
        "id": "zowe_config.html",
        "text": "config",
        "children": [
          {
            "id": "zowe_config_reset.html",
            "text": "reset | re"
          },
          {
            "id": "zowe_config_set.html",
            "text": "set | se"
          }
        ]
      },
      {
        "id": "zowe_db2.html",
        "text": "db2",
        "children": [
          {
            "id": "zowe_db2_call.html",
            "text": "call",
            "children": [
              {
                "id": "zowe_db2_call_procedure.html",
                "text": "procedure | proc | sp"
              }
            ]
          },
          {
            "id": "zowe_db2_execute.html",
            "text": "execute",
            "children": [
              {
                "id": "zowe_db2_execute_sql.html",
                "text": "sql"
              }
            ]
          },
          {
            "id": "zowe_db2_export.html",
            "text": "export",
            "children": [
              {
                "id": "zowe_db2_export_table.html",
                "text": "table"
              }
            ]
          }
        ]
      },
      {
        "id": "zowe_plugins.html",
        "text": "plugins",
        "children": [
          {
            "id": "zowe_plugins_install.html",
            "text": "install"
          },
          {
            "id": "zowe_plugins_list.html",
            "text": "list"
          },
          {
            "id": "zowe_plugins_uninstall.html",
            "text": "uninstall"
          },
          {
            "id": "zowe_plugins_update.html",
            "text": "update"
          },
          {
            "id": "zowe_plugins_validate.html",
            "text": "validate"
          }
        ]
      },
      {
        "id": "zowe_profiles.html",
        "text": "profiles",
        "children": [
          {
            "id": "zowe_profiles_create.html",
            "text": "create | cre",
            "children": [
              {
                "id": "zowe_profiles_create_cics-profile.html",
                "text": "cics-profile | cics"
              },
              {
                "id": "zowe_profiles_create_db2-profile.html",
                "text": "db2-profile | db2"
              },
              {
                "id": "zowe_profiles_create_ssh-profile.html",
                "text": "ssh-profile | ssh"
              },
              {
                "id": "zowe_profiles_create_tso-profile.html",
                "text": "tso-profile | tso"
              },
              {
                "id": "zowe_profiles_create_zosmf-profile.html",
                "text": "zosmf-profile | zosmf"
              }
            ]
          },
          {
            "id": "zowe_profiles_delete.html",
            "text": "delete | rm",
            "children": [
              {
                "id": "zowe_profiles_delete_cics-profile.html",
                "text": "cics-profile | cics"
              },
              {
                "id": "zowe_profiles_delete_db2-profile.html",
                "text": "db2-profile | db2"
              },
              {
                "id": "zowe_profiles_delete_ssh-profile.html",
                "text": "ssh-profile | ssh"
              },
              {
                "id": "zowe_profiles_delete_tso-profile.html",
                "text": "tso-profile | tso"
              },
              {
                "id": "zowe_profiles_delete_zosmf-profile.html",
                "text": "zosmf-profile | zosmf"
              }
            ]
          },
          {
            "id": "zowe_profiles_list.html",
            "text": "list | ls",
            "children": [
              {
                "id": "zowe_profiles_list_cics-profiles.html",
                "text": "cics-profiles | cics"
              },
              {
                "id": "zowe_profiles_list_db2-profiles.html",
                "text": "db2-profiles | db2"
              },
              {
                "id": "zowe_profiles_list_ssh-profiles.html",
                "text": "ssh-profiles | ssh"
              },
              {
                "id": "zowe_profiles_list_tso-profiles.html",
                "text": "tso-profiles | tso"
              },
              {
                "id": "zowe_profiles_list_zosmf-profiles.html",
                "text": "zosmf-profiles | zosmf"
              }
            ]
          },
          {
            "id": "zowe_profiles_set-default.html",
            "text": "set-default | set",
            "children": [
              {
                "id": "zowe_profiles_set-default_cics-profile.html",
                "text": "cics-profile | cics"
              },
              {
                "id": "zowe_profiles_set-default_db2-profile.html",
                "text": "db2-profile | db2"
              },
              {
                "id": "zowe_profiles_set-default_ssh-profile.html",
                "text": "ssh-profile | ssh"
              },
              {
                "id": "zowe_profiles_set-default_tso-profile.html",
                "text": "tso-profile | tso"
              },
              {
                "id": "zowe_profiles_set-default_zosmf-profile.html",
                "text": "zosmf-profile | zosmf"
              }
            ]
          },
          {
            "id": "zowe_profiles_update.html",
            "text": "update | upd",
            "children": [
              {
                "id": "zowe_profiles_update_cics-profile.html",
                "text": "cics-profile | cics"
              },
              {
                "id": "zowe_profiles_update_db2-profile.html",
                "text": "db2-profile | db2"
              },
              {
                "id": "zowe_profiles_update_ssh-profile.html",
                "text": "ssh-profile | ssh"
              },
              {
                "id": "zowe_profiles_update_tso-profile.html",
                "text": "tso-profile | tso"
              },
              {
                "id": "zowe_profiles_update_zosmf-profile.html",
                "text": "zosmf-profile | zosmf"
              }
            ]
          }
        ]
      },
      {
        "id": "zowe_provisioning.html",
        "text": "provisioning | pv",
        "children": [
          {
            "id": "zowe_provisioning_delete.html",
            "text": "delete | del",
            "children": [
              {
                "id": "zowe_provisioning_delete_instance.html",
                "text": "instance | i"
              }
            ]
          },
          {
            "id": "zowe_provisioning_list.html",
            "text": "list | ls",
            "children": [
              {
                "id": "zowe_provisioning_list_catalog-templates.html",
                "text": "catalog-templates | ct"
              },
              {
                "id": "zowe_provisioning_list_instance-info.html",
                "text": "instance-info | ii"
              },
              {
                "id": "zowe_provisioning_list_instance-variables.html",
                "text": "instance-variables | iv"
              },
              {
                "id": "zowe_provisioning_list_registry-instances.html",
                "text": "registry-instances | ri"
              },
              {
                "id": "zowe_provisioning_list_template-info.html",
                "text": "template-info | ti"
              }
            ]
          },
          {
            "id": "zowe_provisioning_perform.html",
            "text": "perform | perf",
            "children": [
              {
                "id": "zowe_provisioning_perform_action.html",
                "text": "action | act"
              }
            ]
          },
          {
            "id": "zowe_provisioning_provision.html",
            "text": "provision | prov",
            "children": [
              {
                "id": "zowe_provisioning_provision_template.html",
                "text": "template | tem"
              }
            ]
          }
        ]
      },
      {
        "id": "zowe_zos-console.html",
        "text": "zos-console | console",
        "children": [
          {
            "id": "zowe_zos-console_collect.html",
            "text": "collect",
            "children": [
              {
                "id": "zowe_zos-console_collect_sync-responses.html",
                "text": "sync-responses | sr"
              }
            ]
          },
          {
            "id": "zowe_zos-console_issue.html",
            "text": "issue",
            "children": [
              {
                "id": "zowe_zos-console_issue_command.html",
                "text": "command | cmd"
              }
            ]
          }
        ]
      },
      {
        "id": "zowe_zos-files.html",
        "text": "zos-files | files",
        "children": [
          {
            "id": "zowe_zos-files_create.html",
            "text": "create | cre",
            "children": [
              {
                "id": "zowe_zos-files_create_data-set-binary.html",
                "text": "data-set-binary | bin"
              },
              {
                "id": "zowe_zos-files_create_data-set-c.html",
                "text": "data-set-c | dsc"
              },
              {
                "id": "zowe_zos-files_create_data-set-classic.html",
                "text": "data-set-classic | classic"
              },
              {
                "id": "zowe_zos-files_create_data-set-partitioned.html",
                "text": "data-set-partitioned | pds"
              },
              {
                "id": "zowe_zos-files_create_data-set-sequential.html",
                "text": "data-set-sequential | ps"
              },
              {
                "id": "zowe_zos-files_create_data-set-vsam.html",
                "text": "data-set-vsam | vsam"
              }
            ]
          },
          {
            "id": "zowe_zos-files_delete.html",
            "text": "delete | del",
            "children": [
              {
                "id": "zowe_zos-files_delete_data-set.html",
                "text": "data-set | ds"
              },
              {
                "id": "zowe_zos-files_delete_data-set-vsam.html",
                "text": "data-set-vsam | vsam"
              },
              {
                "id": "zowe_zos-files_delete_uss-file.html",
                "text": "uss-file | uss"
              }
            ]
          },
          {
            "id": "zowe_zos-files_download.html",
            "text": "download | dl",
            "children": [
              {
                "id": "zowe_zos-files_download_all-members.html",
                "text": "all-members | am"
              },
              {
                "id": "zowe_zos-files_download_data-set.html",
                "text": "data-set | ds"
              },
              {
                "id": "zowe_zos-files_download_uss-file.html",
                "text": "uss-file | uf"
              }
            ]
          },
          {
            "id": "zowe_zos-files_invoke.html",
            "text": "invoke | call",
            "children": [
              {
                "id": "zowe_zos-files_invoke_ams-file.html",
                "text": "ams-file | af"
              },
              {
                "id": "zowe_zos-files_invoke_ams-statements.html",
                "text": "ams-statements | as"
              }
            ]
          },
          {
            "id": "zowe_zos-files_list.html",
            "text": "list | ls",
            "children": [
              {
                "id": "zowe_zos-files_list_all-members.html",
                "text": "all-members | am"
              },
              {
                "id": "zowe_zos-files_list_data-set.html",
                "text": "data-set | ds"
              },
              {
                "id": "zowe_zos-files_list_uss-files.html",
                "text": "uss-files | uss"
              }
            ]
          },
          {
            "id": "zowe_zos-files_upload.html",
            "text": "upload | ul",
            "children": [
              {
                "id": "zowe_zos-files_upload_dir-to-pds.html",
                "text": "dir-to-pds | dtp"
              },
              {
                "id": "zowe_zos-files_upload_dir-to-uss.html",
                "text": "dir-to-uss | dtu"
              },
              {
                "id": "zowe_zos-files_upload_file-to-data-set.html",
                "text": "file-to-data-set | ftds"
              },
              {
                "id": "zowe_zos-files_upload_file-to-uss.html",
                "text": "file-to-uss | ftu"
              },
              {
                "id": "zowe_zos-files_upload_stdin-to-data-set.html",
                "text": "stdin-to-data-set | stds"
              }
            ]
          }
        ]
      },
      {
        "id": "zowe_zos-jobs.html",
        "text": "zos-jobs | jobs",
        "children": [
          {
            "id": "zowe_zos-jobs_cancel.html",
            "text": "cancel | can",
            "children": [
              {
                "id": "zowe_zos-jobs_cancel_job.html",
                "text": "job"
              }
            ]
          },
          {
            "id": "zowe_zos-jobs_delete.html",
            "text": "delete | del",
            "children": [
              {
                "id": "zowe_zos-jobs_delete_job.html",
                "text": "job"
              }
            ]
          },
          {
            "id": "zowe_zos-jobs_download.html",
            "text": "download | dl",
            "children": [
              {
                "id": "zowe_zos-jobs_download_output.html",
                "text": "output | o"
              }
            ]
          },
          {
            "id": "zowe_zos-jobs_list.html",
            "text": "list | ls",
            "children": [
              {
                "id": "zowe_zos-jobs_list_jobs.html",
                "text": "jobs | js"
              },
              {
                "id": "zowe_zos-jobs_list_spool-files-by-jobid.html",
                "text": "spool-files-by-jobid | sfbj"
              }
            ]
          },
          {
            "id": "zowe_zos-jobs_submit.html",
            "text": "submit | sub",
            "children": [
              {
                "id": "zowe_zos-jobs_submit_data-set.html",
                "text": "data-set | ds"
              },
              {
                "id": "zowe_zos-jobs_submit_local-file.html",
                "text": "local-file | lf"
              }
            ]
          },
          {
            "id": "zowe_zos-jobs_view.html",
            "text": "view | vw",
            "children": [
              {
                "id": "zowe_zos-jobs_view_job-status-by-jobid.html",
                "text": "job-status-by-jobid | jsbj"
              },
              {
                "id": "zowe_zos-jobs_view_spool-file-by-id.html",
                "text": "spool-file-by-id | sfbi"
              }
            ]
          }
        ]
      },
      {
        "id": "zowe_zos-tso.html",
        "text": "zos-tso | tso",
        "children": [
          {
            "id": "zowe_zos-tso_issue.html",
            "text": "issue",
            "children": [
              {
                "id": "zowe_zos-tso_issue_command.html",
                "text": "command | cmd"
              }
            ]
          },
          {
            "id": "zowe_zos-tso_ping.html",
            "text": "ping",
            "children": [
              {
                "id": "zowe_zos-tso_ping_address-space.html",
                "text": "address-space | as"
              }
            ]
          },
          {
            "id": "zowe_zos-tso_send.html",
            "text": "send",
            "children": [
              {
                "id": "zowe_zos-tso_send_address-space.html",
                "text": "address-space | as"
              }
            ]
          },
          {
            "id": "zowe_zos-tso_start.html",
            "text": "start | st",
            "children": [
              {
                "id": "zowe_zos-tso_start_address-space.html",
                "text": "address-space | as"
              }
            ]
          },
          {
            "id": "zowe_zos-tso_stop.html",
            "text": "stop | sp",
            "children": [
              {
                "id": "zowe_zos-tso_stop_address-space.html",
                "text": "address-space | as"
              }
            ]
          }
        ]
      },
      {
        "id": "zowe_zos-uss.html",
        "text": "zos-uss | uss",
        "children": [
          {
            "id": "zowe_zos-uss_issue.html",
            "text": "issue | iss",
            "children": [
              {
                "id": "zowe_zos-uss_issue_ssh.html",
                "text": "ssh | ssh"
              }
            ]
          }
        ]
      },
      {
        "id": "zowe_zos-workflows.html",
        "text": "zos-workflows | wf",
        "children": [
          {
            "id": "zowe_zos-workflows_archive.html",
            "text": "archive",
            "children": [
              {
                "id": "zowe_zos-workflows_archive_active-workflow.html",
                "text": "active-workflow | aw"
              }
            ]
          },
          {
            "id": "zowe_zos-workflows_create.html",
            "text": "create | cre",
            "children": [
              {
                "id": "zowe_zos-workflows_create_workflow-from-data-set.html",
                "text": "workflow-from-data-set | wfds"
              },
              {
                "id": "zowe_zos-workflows_create_workflow-from-local-file.html",
                "text": "workflow-from-local-file | wflf"
              },
              {
                "id": "zowe_zos-workflows_create_workflow-from-uss-file.html",
                "text": "workflow-from-uss-file | wfuf"
              }
            ]
          },
          {
            "id": "zowe_zos-workflows_delete.html",
            "text": "delete | del",
            "children": [
              {
                "id": "zowe_zos-workflows_delete_active-workflow.html",
                "text": "active-workflow | aw"
              },
              {
                "id": "zowe_zos-workflows_delete_archived-workflow.html",
                "text": "archived-workflow | arw"
              }
            ]
          },
          {
            "id": "zowe_zos-workflows_list.html",
            "text": "list | ls",
            "children": [
              {
                "id": "zowe_zos-workflows_list_active-workflow-details.html",
                "text": "active-workflow-details | awd"
              },
              {
                "id": "zowe_zos-workflows_list_active-workflows.html",
                "text": "active-workflows | aw"
              },
              {
                "id": "zowe_zos-workflows_list_archived-workflows.html",
                "text": "archived-workflows | arw"
              },
              {
                "id": "zowe_zos-workflows_list_definition-file-details.html",
                "text": "definition-file-details | dfd"
              }
            ]
          },
          {
            "id": "zowe_zos-workflows_start.html",
            "text": "start | sta",
            "children": [
              {
                "id": "zowe_zos-workflows_start_workflow-full.html",
                "text": "workflow-full | wf"
              },
              {
                "id": "zowe_zos-workflows_start_workflow-step.html",
                "text": "workflow-step | ws"
              }
            ]
          }
        ]
      },
      {
        "id": "zowe_zosmf.html",
        "text": "zosmf",
        "children": [
          {
            "id": "zowe_zosmf_check.html",
            "text": "check",
            "children": [
              {
                "id": "zowe_zosmf_check_status.html",
                "text": "status"
              }
            ]
          },
          {
            "id": "zowe_zosmf_list.html",
            "text": "list",
            "children": [
              {
                "id": "zowe_zosmf_list_systems.html",
                "text": "systems"
              }
            ]
          }
        ]
      }
    ]
  }
];
const aliasList = {
  "def": [
    "define"
  ],
  "prog": [
    "program"
  ],
  "tran": [
    "transaction"
  ],
  "del": [
    "delete"
  ],
  "dis": [
    "discard"
  ],
  "res": [
    "resource"
  ],
  "ins": [
    "install"
  ],
  "ref": [
    "refresh"
  ],
  "re": [
    "reset"
  ],
  "se": [
    "set"
  ],
  "proc": [
    "procedure"
  ],
  "sp": [
    "procedure",
    "stop"
  ],
  "cre": [
    "create"
  ],
  "cics": [
    "cics-profile",
    "cics-profiles"
  ],
  "db2": [
    "db2-profile",
    "db2-profiles"
  ],
  "ssh": [
    "ssh-profile",
    "ssh-profiles"
  ],
  "tso": [
    "tso-profile",
    "tso-profiles",
    "zos-tso"
  ],
  "zosmf": [
    "zosmf-profile",
    "zosmf-profiles"
  ],
  "rm": [
    "delete"
  ],
  "ls": [
    "list"
  ],
  "set": [
    "set-default"
  ],
  "upd": [
    "update"
  ],
  "pv": [
    "provisioning"
  ],
  "i": [
    "instance"
  ],
  "ct": [
    "catalog-templates"
  ],
  "ii": [
    "instance-info"
  ],
  "iv": [
    "instance-variables"
  ],
  "ri": [
    "registry-instances"
  ],
  "ti": [
    "template-info"
  ],
  "perf": [
    "perform"
  ],
  "act": [
    "action"
  ],
  "prov": [
    "provision"
  ],
  "tem": [
    "template"
  ],
  "console": [
    "zos-console"
  ],
  "sr": [
    "sync-responses"
  ],
  "cmd": [
    "command"
  ],
  "files": [
    "zos-files"
  ],
  "bin": [
    "data-set-binary"
  ],
  "dsc": [
    "data-set-c"
  ],
  "classic": [
    "data-set-classic"
  ],
  "pds": [
    "data-set-partitioned"
  ],
  "ps": [
    "data-set-sequential"
  ],
  "vsam": [
    "data-set-vsam"
  ],
  "ds": [
    "data-set"
  ],
  "uss": [
    "uss-file",
    "uss-files",
    "zos-uss"
  ],
  "dl": [
    "download"
  ],
  "am": [
    "all-members"
  ],
  "uf": [
    "uss-file"
  ],
  "call": [
    "invoke"
  ],
  "af": [
    "ams-file"
  ],
  "as": [
    "ams-statements",
    "address-space"
  ],
  "ul": [
    "upload"
  ],
  "dtp": [
    "dir-to-pds"
  ],
  "dtu": [
    "dir-to-uss"
  ],
  "ftds": [
    "file-to-data-set"
  ],
  "ftu": [
    "file-to-uss"
  ],
  "stds": [
    "stdin-to-data-set"
  ],
  "jobs": [
    "zos-jobs"
  ],
  "can": [
    "cancel"
  ],
  "o": [
    "output"
  ],
  "js": [
    "jobs"
  ],
  "sfbj": [
    "spool-files-by-jobid"
  ],
  "sub": [
    "submit"
  ],
  "lf": [
    "local-file"
  ],
  "vw": [
    "view"
  ],
  "jsbj": [
    "job-status-by-jobid"
  ],
  "sfbi": [
    "spool-file-by-id"
  ],
  "st": [
    "start"
  ],
  "iss": [
    "issue"
  ],
  "wf": [
    "zos-workflows",
    "workflow-full"
  ],
  "aw": [
    "active-workflow",
    "active-workflows"
  ],
  "wfds": [
    "workflow-from-data-set"
  ],
  "wflf": [
    "workflow-from-local-file"
  ],
  "wfuf": [
    "workflow-from-uss-file"
  ],
  "arw": [
    "archived-workflow",
    "archived-workflows"
  ],
  "awd": [
    "active-workflow-details"
  ],
  "dfd": [
    "definition-file-details"
  ],
  "sta": [
    "start"
  ],
  "ws": [
    "workflow-step"
  ]
};
const cmdToLoad = null;